CCDNUser\SecurityBundle\Entity\Session:
    type: entity
    table: cc_security_session
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        ipAddress:
            type: string
            column: ip_address
            length: 50
        loginAttemptDate:
            type: datetime
            column: login_attempt_date
        loginAttemptUsername:
            type: text
            column: login_attempt_username
    indexes: 
        cc_security_idx: 
            columns: [ ip_address ]